# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2

  # Maintain dependencies for poetry
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5