name: "update-jira-labels-and-components"
description: "Get started with Python Container actions"
author: "=Byeongcheol Kim"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"